### PR TITLE
add swr and some structure

### PR DESCRIPTION
**Pull request by PaulJohannFlade**

### CODE REVIEW

**Comment by ladydarkja** [comment]
LGTM!

**Review by FelineHuhn — CHANGES_REQUESTED** [review]
Great, you got the data with swr 😍🎉 But I think, the user story isn't finished. Please reread ALL acceptance criteria and tasks, that must be done, before giving the code in review :)

**Comment by Xristof23** [comment]
We should have named that commit better. We only made the commit and push to switch the driver. We are aware that tha user story is not finished. By the way: The name of the commit is not: "User story 1 is finished".  ;)

**Comment by FelineHuhn** [comment]
> We should have named that commit better. We only made the commit and push to switch. We are aware that tha user story is not finished.

Allright, I understand now :)  Please post the PR for the code review, when the whole user story is finshed, we do not need a code review for single commits. But your work so far looks great! Keep up the good work! :)

**Pull request merged**
